=== giannyuffo/Lenguaje-de-marcas/Segunda Eva/Esquemas/2/2curso.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
    <xs:element name="Lista">
       <xs:complexType> <!-- lista es complejo porque contiene elementos -->
           <xs:sequence>
             <xs:element name="Curso" maxOccurs="unbounded">
               <xs:complexType>  <!-- curso es complejo porque contiene elementos -->
                 <xs:sequence>
                               <xs:element name="Titulo" type="xs:string" maxOccurs="3" />
        					   <xs:element name="descripcion">
        						   <xs:simpleType>
        									<xs:restriction base="xs:string">
        										<xs:length value="10"/>
        									</xs:restriction>
        							</xs:simpleType>
        					   </xs:element>
                               <xs:element name="Horas" type="xs:nonNegativeInteger"/>
        					   <xs:element name="observaciones">
        							<xs:simpleType>
        								<xs:restriction base="xs:string">
        									<xs:minLength value="3"/>
        									<xs:maxLength value="8"/>
        								</xs:restriction>
        							</xs:simpleType>
        					   </xs:element>
        					   <xs:element name="grupo" minOccurs="0">
        							<xs:simpleType>
        								<xs:restriction base="xs:string">
        									<xs:enumeration value="DAM1"/>
        									<xs:enumeration value="DAM2"/>
        									<xs:enumeration value="ASI1"/>
        									<xs:enumeration value="ASI2"/>
        								</xs:restriction>
        							</xs:simpleType>
        					   </xs:element>
        					   <xs:element name="precio" type="tipoPrecio"/>
        						 <xs:element name="precio2" type="tipoPrecio"/>
                     <xs:element name="precio3" type="tipoPrecio"/>
                 </xs:sequence>
              </xs:complexType>
             </xs:element>

             <xs:simpleType name="precio">
               <xs:restriction base="xs:nonNegativeInteger">
                 <xs:minInclusive value="100"/>
                 <xs:maxInclusive value="150"/>
               </xs:restriction>
             </xs:simpleType>

           </xs:sequence>
       </xs:complexType>
    </xs:element>
</xs:schema>

=== giannyuffo/Lenguaje-de-marcas/Segunda Eva/Esquemas/2/2curso.xml
<?xml version="1.0" encoding="utf-8"?>
 <Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="2curso.xsd">
<Curso>
		<Titulo>Lenguaje de Marcas</Titulo>
		<descripcion>0123456789</descripcion> <!--cadema de caracteres de longitud 10-->
		<Horas>200</Horas>
		<observaciones>abc</observaciones>  <!-- cadena de entre 3 y 8 caracteres-->
		<grupo>DAM1</grupo> <!-- opciones: dam1 dam2 asi1, asi2-->
		<precio>120</precio> <!-- entre 100 y 150 incluidos-->
		<precio2>120</precio2>
    <precio3>120</precio3>
    <turno></turno> <!-- maÃ±ana o de tarde definido dentro-->
    <precioMaximo></precioMaximo><!-- un numero positivo mayor o igual que 1-->
    <precioMinimo></precioMinimo><!-- un numero entre 20 (no incluido) y 30(no incluidos)-->
	</Curso>
	<Curso>
		<Titulo>BBDD</Titulo>
		<descripcion>0123456789</descripcion>
		<Horas>210</Horas>
		<observaciones>abcd</observaciones>
<!--		<grupo>ASI2</grupo>-->
		<precio>120</precio>
	</Curso>
 </Lista>
