=== giannyuffo/Lenguaje-de-marcas/Segunda Eva/Esquemas/1/curso.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.w3.org/2001/XMLSchema.xsd"
>
    <xs:element name="Lista">
       <xs:complexType> <!-- lista es complejo porque contiene elementos -->
           <xs:sequence>
             <xs:element name="Curso" maxOccurs="unbounded">
               <xs:complexType>  <!-- curso es complejo porque contiene elementos -->
                 <xs:sequence>
                       <xs:element name="Titulo" type="xs:string"/>
                       <xs:element name="Horas" type="xs:nonNegativeInteger"/>
                       <xs:element name="fechaComienzo" type="xs:date"></xs:element>
                       <xs:element name="precio" type="xs:nonNegativeInteger"></xs:element>
                       <xs:element name="numeroProfesores" type="nonNegativeInteger"></xs:element>
                       <xs:element name="horaComienzo" type="xs:time"></xs:element>
                       <xs:element name="fechaFinHora" type="xs:dateTime"></xs:element>
                       <xs:element name="presencial" type="xs:boolean"></xs:element>

                 </xs:sequence>
              </xs:complexType>
             </xs:element>
           </xs:sequence>
       </xs:complexType>
    </xs:element>
</xs:schema>


<!--  Estructura:
    Lista: es una secuencia de un solo elemento:curso
         Curso* : es una secuencia de dos elementos:titulo y horas. El curso se repite.
              Titulo
              Horas
              fechaComienzo
              precio
              numeroProfesores
              horaComienzo
              fechaFinHora
              presencial
         Curso*
              TÃ­tulo
              Horas
              fechaComienzo
              precio
              numeroProfesores
              horaComienzo
              fechaFinHora
              presencial
 -->

=== giannyuffo/Lenguaje-de-marcas/Segunda Eva/Esquemas/1/1curso.xml
<?xml version="1.0" encoding="utf-8"?>
 <Lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="curso.xsd">
  	<Curso>
  		<Titulo>Lenguaje de Marcas</Titulo> entre 1 y 3 titulos
  		<Horas>200</Horas>
      <fechaComienzo>2020-02-13</fechaComienzo>
      <precio>100</precio> que aparezca dos veces
      <numeroProfesores>3</numeroProfesores>
      <horaComienzo>14:00:00</horaComienzo>
      <fechaFinHora>2020-02-13T14:00:00</fechaFinHora>
      <presencial>true</presencial> opcional
  	</Curso>
  	<Curso>
  		<Titulo>BBDD</Titulo>
  		<Horas>210</Horas>
      <fechaComienzo>2020-02-14</fechaComienzo>
      <precio>200</precio>
      <numeroProfesores>2</numeroProfesores>
      <horaComienzo>13:10:00</horaComienzo>
      <fechaFinHora>2020-02-14T13:10:00</fechaFinHora>
      <presencial>true</presencial>

  	</Curso>
  </Lista>
